### ISSUE TITLE
More descreet extension toggle

### ISSUE THREAD

**Issue by martinsvoboda1101** [yannprada/cookie-garden-helper#3]
Hi, I'm loving the mod so far, works well for me.

I have just one cosmetic request - the "Cookie Garden Helper" toggle is really big, taking up a lot of space and is kinda annoying to look at.

Would it be possible to move it, for example, next to the "Close Garden" button?

Thanks for the mod!

**Comment by yannprada** [comment]
Hi,
Thanks for your feedback! I've done as requested, (see #4), and it's looks so great!
